
var menuInfo = {};

menuInfo.menu = [
    { brand: 'nfsq', display_name: '农夫山泉', active: '' },
    { brand: 'dnmd', display_name: '达能-脉动', active: '' },
    { brand: 'sdl', display_name: '三得利', active: '' },
    { brand: 'sm', display_name: '申美', active: '' },
    { brand: 'bs', display_name: '百事', active: '' },
    { brand: 'ty', display_name: '统一', active: '' },
    { brand: 'wlj', display_name: '王老吉', active: '' },
    { brand: 'wt', display_name: '维他', active: '' },
    { brand: 'bss', display_name: '百岁山', active: '' },
    { brand: 'yb', display_name: '怡宝', active: '' },
    { brand: 'hn', display_name: '红牛', active: '' },
]


menuInfo.lists = {
    nfsq: [
        { display_name: '农夫山泉', quat: '380ml', quat_num: '24', price: '36', active: '' },
        { display_name: '农夫山泉', quat: '550ml', quat_num: '28', price: '39', active: '' },
        { display_name: '农夫山泉', quat: '1.5L', quat_num: '12', price: '38', active: '' },
        { display_name: '农夫山泉', quat: '4L', quat_num: '4', price: '36', active: '' },
        { display_name: '农夫山泉', quat: '4L', quat_num: '6', price: '45.5', active: '' },
        { display_name: '水溶柠檬', quat: '445ml', quat_num: '24', price: '97', active: '' },
        { display_name: '水溶西柚', quat: '445ml', quat_num: '24', price: '97', active: '' },
        { display_name: '水溶青皮', quat: '445ml', quat_num: '24', price: '97', active: '' },
        { display_name: '东方树叶茉莉', quat: '500ml', quat_num: '24', price: '102', active: '' },
        { display_name: '东方树叶乌龙', quat: '500ml', quat_num: '24', price: '102', active: '' },
        { display_name: '东方树叶红茶', quat: '500ml', quat_num: '24', price: '102', active: '' },
        { display_name: '东方树叶绿茶', quat: '500ml', quat_num: '24', price: '102', active: '' },
        { display_name: '维他命柠檬', quat: '500ml', quat_num: '24', price: '89', active: '' },
        { display_name: '维他命柑橘', quat: '500ml', quat_num: '24', price: '89', active: '' },
        { display_name: '维他命蓝莓', quat: '500ml', quat_num: '24', price: '89', active: '' },
        { display_name: 'NFC橙汁百分百', quat: '300ml', quat_num: '24', price: '156', active: '' },
        { display_name: '茶Π蜜桃乌龙', quat: '500ml', quat_num: '24', price: '89', active: '' },
        { display_name: '茶Π柠檬红茶', quat: '500ml', quat_num: '24', price: '89', active: '' },
        { display_name: '尖叫纤维', quat: '500ml', quat_num: '24', price: '97', active: '' },
        { display_name: '尖叫多肽', quat: '500ml', quat_num: '24', price: '97', active: '' },
    ],
    dnmd: [
        { display_name: '脉动水蜜桃', quat: '600ml', quat_num: '15', price: '59', active: '' },
        { display_name: '脉动青柠', quat: '600ml', quat_num: '15', price: '59', active: '' },
        { display_name: '脉动芒果', quat: '600ml', quat_num: '15', price: '59', active: '' },
        { display_name: '脉动橘子', quat: '600ml', quat_num: '15', price: '59', active: '' },
        { display_name: '脉动菠萝', quat: '600ml', quat_num: '15', price: '59', active: '' },
        { display_name: '脉动椰子菠萝', quat: '600ml', quat_num: '15', price: '59', active: '' },
    ],
    sdl: [
        { display_name: '沁柠水', quat: '550ml', quat_num: '15', price: '52.5', active: '' },
        { display_name: '三得利无糖乌龙茶', quat: '550ml', quat_num: '15', price: '52.5', active: '' },
        { display_name: '三得利低糖乌龙茶', quat: '550ml', quat_num: '15', price: '52.5', active: '' },
        { display_name: '黑乌龙', quat: '350ml', quat_num: '24', price: '144', active: '' },
        { display_name: '三得利无糖乌龙', quat: '1.25L', quat_num: '12', price: '84', active: '' },
    ],
    sm: [
        { display_name: '可口可乐', quat: '300ml', quat_num: '24', price: '47', active: '' },
        { display_name: '可口可乐', quat: '330ml', quat_num: '24', price: '60', active: '' },
        { display_name: '可口可乐', quat: '600ml', quat_num: '24', price: '72', active: '' },
        { display_name: '可口可乐', quat: '1.25L', quat_num: '12', price: '64.6', active: '' },
        { display_name: '可口可乐', quat: '2L', quat_num: '6', price: '42', active: '' },
        { display_name: '雪碧', quat: '300ml', quat_num: '24', price: '47', active: '' },
        { display_name: '雪碧', quat: '330ml', quat_num: '24', price: '60', active: '' },
        { display_name: '雪碧', quat: '600ml', quat_num: '24', price: '72', active: '' },
        { display_name: '雪碧', quat: '1.25L', quat_num: '12', price: '64.6', active: '' },
        { display_name: '雪碧', quat: '2L', quat_num: '6', price: '47', active: '' },
        { display_name: '果粒橙', quat: '450ml', quat_num: '24', price: '74', active: '' },
        { display_name: '果粒橙', quat: '1.25L', quat_num: '12', price: '78', active: '' },
        { display_name: '芬达-橙', quat: '600ml', quat_num: '12', price: '42', active: '' },
        { display_name: '芬达-苹果', quat: '600ml', quat_num: '12', price: '42', active: '' },
        { display_name: '芬达-水蜜桃', quat: '600ml', quat_num: '12', price: '42', active: '' },
        { display_name: '怡泉苏打水', quat: '330ml', quat_num: '24', price: '81', active: '' },
        { display_name: '怡泉干姜水', quat: '330ml', quat_num: '24', price: '81', active: '' },
        { display_name: '怡泉汤力水', quat: '330ml', quat_num: '24', price: '81', active: '' },
        { display_name: '加C柠檬', quat: '330ml', quat_num: '24', price: '82', active: '' },
        { display_name: '加C柠檬', quat: '500ml', quat_num: '12', price: '48', active: '' },
    ],
    bs: [
        { display_name: '百事可乐', quat: '330ml', quat_num: '24', price: '57', active: '' },
        { display_name: '百事可乐', quat: '600ml', quat_num: '24', price: '67', active: '' },
        { display_name: '百事可乐', quat: '2L', quat_num: '6', price: '42', active: '' },
        { display_name: '美年达', quat: '330ml', quat_num: '24', price: '57', active: '' },
        { display_name: '美年达', quat: '600ml', quat_num: '24', price: '67', active: '' },
        { display_name: '美年达', quat: '2L', quat_num: '6', price: '42', active: '' },
        { display_name: '七喜', quat: '330ml', quat_num: '24', price: '47', active: '' },
        { display_name: '七喜', quat: '2L', quat_num: '6', price: '42', active: '' },
        { display_name: '佳得乐橙味', quat: '600ml', quat_num: '15', price: '59', active: '' },
        { display_name: '佳得乐柠檬', quat: '600ml', quat_num: '15', price: '59', active: '' },
        { display_name: '佳得乐蓝莓', quat: '600ml', quat_num: '15', price: '59', active: '' },
        { display_name: '佳得乐西柚', quat: '600ml', quat_num: '15', price: '59', active: '' },
    ],
    ty: [
        { display_name: '冰红茶', quat: '500ml', quat_num: '18', price: '49', active: '' },
        { display_name: '冰红茶', quat: '1L', quat_num: '8', price: '40', active: '' },
        { display_name: '冰红茶', quat: '2L', quat_num: '6', price: '45', active: '' },
        { display_name: '绿茶', quat: '500ml', quat_num: '18', price: '49', active: '' },
        { display_name: '绿茶', quat: '1L', quat_num: '8', price: '40', active: '' },
        { display_name: '绿茶', quat: '2L', quat_num: '6', price: '45', active: '' },
        { display_name: '小茗同学青柠', quat: '450ml', quat_num: '15', price: '69', active: '' },
        { display_name: '小茗同学冰菊', quat: '450ml', quat_num: '15', price: '69', active: '' },
        { display_name: '小茗同学溜溜哒', quat: '450ml', quat_num: '15', price: '69', active: '' },
        { display_name: '小茗同学乌龙茶', quat: '450ml', quat_num: '15', price: '69', active: '' },
        { display_name: '鲜橙多', quat: '450ml', quat_num: '15', price: '52.5', active: '' },
        { display_name: 'ALKAQUA矿泉水', quat: '570ml', quat_num: '24', price: '79', active: '' },
        { display_name: '冰糖雪梨', quat: '500ml', quat_num: '15', price: '52.5', active: '' },
    ],
    wlj: [
        { display_name: '王老吉', quat: '310ml', quat_num: '24', price: '65', active: '' },
        { display_name: '王老吉', quat: '500ml', quat_num: '15', price: '57', active: '' },
    ],
    wt: [
        { display_name: '维他柠檬水', quat: '250ml', quat_num: '24', price: '61.5', active: '' },
        { display_name: '维他柠檬水', quat: '500ml', quat_num: '24', price: '116', active: '' },
    ],
    bss: [
        { display_name: '景田百岁山水', quat: '348ml', quat_num: '24', price: '42', active: '' },
        { display_name: '景田百岁山水', quat: '570ml', quat_num: '24', price: '52', active: '' },
    ],
    yb: [

        { display_name: '怡宝矿泉水', quat: '350ml', quat_num: '24', price: '39', active: '' },
        { display_name: '怡宝矿泉水', quat: '555ml', quat_num: '24', price: '42', active: '' },
        { display_name: '怡宝矿泉水', quat: '1.55L', quat_num: '12', price: '44', active: '' },
        { display_name: '怡宝矿泉水', quat: '4.5L', quat_num: '4', price: '45', active: '' },
    ],
    hn: [

        { display_name: '红牛', quat: '250ml', quat_num: '24', price: '132', active: '' },
    ],
};
export default menuInfo;